### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by davideprevosto** [davidwebca/custom-editor-sidebar-width#2]
Thank you for your idea and for the plugin. 

Unfortunately I catch an error in the ACF Option field group pages.

```
Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.<anonymous> (media-audiovideo.js?ver=5.7.2:211)
    at __webpack_require__ (media-audiovideo.js?ver=5.7.2:20)
    at Object.<anonymous> (media-audiovideo.js?ver=5.7.2:91)
    at __webpack_require__ (media-audiovideo.js?ver=5.7.2:20)
    at media-audiovideo.js?ver=5.7.2:84
    at media-audiovideo.js?ver=5.7.2:87
```

Have you got any evidence on this?

Regards

**Comment by davidwebca** [comment]
I got you. I discovered a compilation problem from webpack / laravel mix. When other JS codes that were compiled through Laravel Mix or Webpack are used and JS is added in the same way, their webpack chunk name can collide. I'll name my package.json and recompile, it should fix the issue.

**Comment by davideprevosto** [comment]
> I got you. I discovered a compilation problem from webpack / laravel mix. When other JS codes that were compiled through Laravel Mix or Webpack are used and JS is added in the same way, their webpack chunk name can collide. I'll name my package.json and recompile, it should fix the issue.

Unfortunately it seems the error is still there, in my case.

Thank you
